using AVSupplier.Application.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AVSupplier.Application.Interfaces
{
    public interface IAutoGeneratedNumberRepository
    {
        Task<string?> GetAutoGeneratedNumber(AutoGenerateNumber_Request parameter);
    }
}
